name: eddi
services:
  db:
    image: pgvector/pgvector:pg16 # https://github.com/pgvector/pgvector 
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eddi
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata:
